# Generated by Django 4.2.8 on 2023-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_paragraph', models.CharField(max_length=500)),
                ('second_paragraph', models.CharField(max_length=500)),
                ('about_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
