# Generated by Django 4.2.8 on 2023-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('descreption', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutSectionDetails',
            new_name='AboutSectionDetail',
        ),
    ]
