# Generated by Django 4.2.8 on 2023-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_servicesectiondetail_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsectiondetail',
            name='resume',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
