# Generated by Django 4.2.8 on 2023-12-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_aboutsectiondetail_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='images')),
                ('project_link', models.CharField(max_length=300)),
            ],
        ),
    ]
