# Generated by Django 4.2.8 on 2024-01-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_aboutsectiondetail_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsectiondetail',
            name='resume',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
