# Generated by Django 4.2.8 on 2024-01-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_aboutsectiondetail_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsectiondetail',
            name='about_image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutsectiondetail',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='projectsectiondetail',
            name='project_image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
