# Generated by Django 4.2.8 on 2024-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_aboutsectiondetail_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.CharField(max_length=25)),
                ('info_icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
