# Generated by Django 4.2.8 on 2024-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_personallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsectiondetail',
            name='resume_icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
