# Generated by Django 4.2.8 on 2024-01-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_aboutsectiondetail_resume_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default=None, max_length=20)),
                ('skill_image', models.ImageField(default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
